travis ci

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,21 +1,25 @@
 #!/bin/sh
-set -xe
+# set -xe
+
+echo "Running dry-run"
+rsync --dry-run -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p $PORT" ./ "$USERNAME"@"$HOST":"$PROJECT"
 
 # if [ $TRAVIS_BRANCH == 'recette' ]; then
-$ERRORSTRING="Error. Please make sure you've indicated correct parameters"
-if [ $# -eq 0 ]; then
-	echo $ERRORSTRING
-elif [ $1 == "live" ]; then
-	if [[ -z $2 ]]; then
-		echo "Running dry-run"
-		rsync --dry-run -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p $PORT" ./ $USERNAME@$HOST:$PROJECT
-	elif [ $2 == "go" ]; then
-		echo "Running actual deploy"
-		rsync -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p $PORT" ./ $USERNAME@$HOST:$PROJECT
-	else
-		echo $ERRORSTRING
-	fi
-fi
+# ERRORSTRING="Error. Please make sure you've indicated correct parameters"
+
+# if [ $# -eq 0 ]; then
+# 	echo "$ERRORSTRING"
+# elif [[ "$1" == "live" ]]; then
+# 	if [[ -z $2 ]]; then
+# 		echo "Running dry-run"
+# 		rsync --dry-run -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p $PORT" ./ "$USERNAME"@"$HOST":"$PROJECT"
+# 	elif [[ "$2" == "go" ]]; then
+# 		echo "Running actual deploy"
+# 		rsync -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p $PORT" ./ "$USERNAME"@"$HOST":"$PROJECT"
+# 	else
+# 		echo "$ERRORSTRING"
+# 	fi
+# fi
 # else
 # 	echo "Not deploying, since this branch isn't recette."
 # fi
